In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([ 0.35860753,  0.23992432, -1.08766139, -0.84826966, -1.04873677,
        0.23818986,  0.35328475, -0.13372196,  1.07558692, -0.0133091 ])

In [9]:
B = np.random.rand(10)
B

array([ 0.20502832,  0.76735707,  0.42379088,  0.89099161,  0.95844558,
        0.2816587 ,  0.4692233 ,  0.63607761,  0.76037984,  0.01539643])

In [10]:
# Binary Functions
np.add(A,B)

array([ 0.56363585,  1.00728139, -0.66387051,  0.04272196, -0.09029119,
        0.51984857,  0.82250804,  0.50235565,  1.83596676,  0.00208733])

In [12]:
# Compares max of every index
np.maximum(A,B)

array([ 0.35860753,  0.76735707,  0.42379088,  0.89099161,  0.95844558,
        0.2816587 ,  0.4692233 ,  0.63607761,  1.07558692,  0.01539643])

In [13]:
np.minimum(A,B)

array([ 0.20502832,  0.23992432, -1.08766139, -0.84826966, -1.04873677,
        0.23818986,  0.35328475, -0.13372196,  0.76037984, -0.0133091 ])

In [14]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True